### ISSUE TITLE
parameters 이슈

### ISSUE THREAD

**Issue by seyoki** [seyoki/rang#1]
Name for argument of type [java.lang.String] not specified, and parameter name information not available via reflection. Ensure that the compiler uses the '-parameters' flag.
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.updateNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:186) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.getNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:161) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:107) ~[spring-web-6.1.5.jar:6.1.5]
이상하다 STS는 같은 워크스페이스의 기능들이 모두공유되나보다 다른프로젝트에있던 에러가 똑같이 적용되는것을 알수있다
requestParam을 쓰지않았는데도 java.lang. -parameters 에러가 발생했다 그래서 해결책을 찾아보려한다.

해결: @RequestParam(name="")String title)
STS의경우 gradle에 compile을 해주면된다 
@RequestParam은 Spring MVC에서 클라이언트의 HTTP 요청 파라미터를 컨트롤러 메소드의 파라미터로 바인딩하려고 할 때 사용되는 어노테이션이다.

@RequestParam("id") id라는 이름의 파라미터를 찾아, Integer id에 바인딩 한다.

나의 경우 파라미터 이름 정보가 클래스 파일에 포함되지 않아서 발생했고, 명시적으로 요청 파라미터의 이름을 지정해주었다.
@RequestParam(”id”) 어노테이션을 추가해서, id라는 이름의 요청 파라미터를 찾아 Integer에 바인딩 하도록 지정했다. 그리고 해결했다.

**Comment by seyoki** [comment]
21:55:53	CREATE PROCEDURE loopInsert() BEGIN     DECLARE i INT DEFAULT 1;     WHILE i <= 130 DO         INSERT INTO board(title,content)           VALUES(concat('제목',i), concat('내용',i));         SET i = i + 1;     END WHILE; END	0 row(s) affected	0.016 sec
프로시저가 만들어지긴하는데 자꾸 0row가 뜬다 왜이렇지...
해결책을 찾아보자: 
보통의 INSERT 쿼리에서, (데이터 1개 INSERT)

INSERT INTO test.test (column1, column2, ...) VALUES (value1, value2, ...)

이런식으로 쿼리를 작성하면

affected rows = 0 : INSERT 실패. 쿼리에 문제가 없다면 보통은 키가 중복되어서 발생.

affected rows = 1 : INSERT 성공.

affected rows > 1 : 심각한 문제. (사실 이럴 가능성은 0이라고 보면 된다. 이런 상황이 온다면, 쿼리나 모듈 어딘가에 문제가 있는 것이다.)
[출처] [Mysql affected rows](https://blog.naver.com/merong5780/40109489643)|작성자 [메롱](https://blog.naver.com/merong5780)
row가 0인 경우 최종 상태에 업데이트 할 row가 없는 것으로 인식 0을 반환한다
![image](https://github.com/seyoki/rang/assets/159132449/fe776748-b54a-48ab-a014-76815ac353af)

default값을 변경하면  insert쿼리가 변경되서 update되고 다시 초록색 아이콘이 뜨는데 여전히 row는 0인상태 
더찾아봐야겠다
